# -*- coding: utf-8 -*-
"""Pro_econ_w.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBgUiNf_9LEsEFihv9iXSq0tvAYMKMn1

# Modelo y análsis

### Pquetes
"""

# ---------- 0) Paquetes ----------
pkgs = ["pandas", "numpy", "matplotlib", "seaborn", "statsmodels", "scipy"]

import subprocess, sys
for p in pkgs:
    try: __import__(p)
    except: subprocess.run([sys.executable, "-m", "pip", "install", p], capture_output=True)

import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
import statsmodels.api as sm, statsmodels.formula.api as smf
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

print("\n[OK] Paquetes listos.")

"""### Preparar y cargar datos"""

df = pd.read_excel('/content/Data.xlsx')
df.to_csv('data.csv', index=False)            #Por costumbre lo trabajé en csv
print("Excel convertido a CSV exitosamente")
print("=" *60)

# Reemplazar comas por puntos y asegurar numéricos
df = df.apply(lambda x: x.astype(str).str.replace(',', '.'))
df = df.apply(pd.to_numeric, errors='coerce')
print(df.dtypes)

print("=" *60)
print("\n[OK] Datos listos.")

df.head()

"""### Resumen de estadísticos"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Resumen de principales estadísticos
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
print("Resumen estadístico de las variables:")
print(df[['lnsalario', 'educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']].describe())

"""### Gráficos"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Revisión de gráfico
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Boxplot/violin-like por sexo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Boxplot
sns.boxplot(x='femenino', y='lnsalario', data=df, ax=ax1)
ax1.set_title('ln(salario) por sexo')
ax1.set_ylabel('ln(salario)')
ax1.set_xlabel('Sexo (0=Masculino, 1=Femenino)')

# Violin plot
sns.violinplot(x='femenino', y='lnsalario', data=df, ax=ax2)
sns.stripplot(x='femenino', y='lnsalario', data=df, alpha=0.3, jitter=True, ax=ax2)
ax2.set_title('ln(salario) por sexo ')
ax2.set_ylabel('ln(salario)')
ax2.set_xlabel('Sexo (0=Masculino, 1=Femenino)')

plt.tight_layout()
plt.show()

# lnsalari - escol
plt.figure(figsize=(10, 6))
sns.regplot(x='educ', y='lnsalario', data=df,
            scatter_kws={'alpha':0.4, 's':30},
            lowess=True,
            line_kws={'color':'red'})
plt.title('Relación ln(salario) – educación')
plt.xlabel('Años de educación')
plt.ylabel('ln(salario)')
plt.show()

# lnsalario - edad
plt.figure(figsize=(10, 6))
sns.regplot(x='edad', y='lnsalario', data=df,
            scatter_kws={'alpha':0.35, 's':30},
            order=2,
            ci=95)
plt.title('Relación ln(salario) – edad ')
plt.xlabel('Edad')
plt.ylabel('ln(salario)')
plt.show()

# Densidades  por género
plt.figure(figsize=(10, 6))
sns.kdeplot(data=df[df['femenino'] == 1], x='lnsalario', label='Femenino', linewidth=2)
sns.kdeplot(data=df[df['femenino'] == 0], x='lnsalario', label='Masculino', linestyle='--', linewidth=2)
plt.title('Distribuciones de ln(salario) por género')
plt.xlabel('ln(salario)')
plt.legend()
plt.show()

# Matriz de dispersión
variables = ['lnsalario', 'educ', 'edad', 'edad2']
sns.pairplot(df[variables], diag_kind='kde', corner=True)
plt.suptitle('Matriz de dispersión ', y=1.02)
plt.show()

"""### Regresiones"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Análisis de Regresiones
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Modelos
model1 = smf.ols('lnsalario ~ educ', data=df).fit()
model2 = smf.ols('lnsalario ~ educ + edad + edad2 + urban', data=df).fit()
model3 = smf.ols('lnsalario ~ educ + edad + edad2 + urban + casado + femenino', data=df).fit()

# Para interacción
df['educxfemenino'] = df['educ'] * df['femenino']
model4 = smf.ols('lnsalario ~ educ + edad + edad2 + urban + casado + femenino + educxfemenino', data=df).fit()

# Mostrar resultados
print("=== MODELO 1 ===")
print(model1.summary())
print("\n=== MODELO 2 ===")
print(model2.summary())
print("\n=== MODELO 3 ===")
print(model3.summary())
print("\n=== MODELO 4 ===")
print(model4.summary())

# AIC y BIC
models = [model1, model2, model3, model4]
model_names = ['Model1', 'Model2', 'Model3', 'Model4']

aic_bic = pd.DataFrame({
    'Modelo': model_names,
    'AIC': [model.aic for model in models],
    'BIC': [model.bic for model in models],
    'R2_ajustado': [model.rsquared_adj for model in models]
})
print("\n=== COMPARACIÓN DE MODELOS (AIC/BIC) ===")
print(aic_bic)

"""### Hipótesis"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Pruebas de hipótesis
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Para ipótesis individual
print("\n=== PRUEBA PARA femenino ===")
print(f"Coeficiente femenino: {model3.params['femenino']:.4f}")
print(f"Valor-t: {model3.tvalues['femenino']:.4f}")
print(f"P-valor: {model3.pvalues['femenino']:.4f}")

# Test conjunta
hypothesis_inter = 'i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0'
f_test_inter = model_interacciones.f_test(hypothesis_inter)
print(f"\n=== INTERACCIONES CONJUNTAS ===")
print(f"Estadístico F: {f_test_inter.fvalue:.4f}")  # Cambio aquí
print(f"P-valor: {f_test_inter.pvalue:.4f}")
print(f"Grados de libertad: {f_test_inter.df_num}, {f_test_inter.df_denom}")

# Óptimo de edad
edad_coef = model3.params['edad']
edad2_coef = model3.params['edad2']
edad_optima = -edad_coef / (2 * edad2_coef)
diferencia = edad_optima - 50

print(f"\n=== EDAD ÓPTIMA ===")
print(f"Edad que maximiza salario: {edad_optima:.2f}")
print(f"Diferencia con 50: {diferencia:.2f}")

# Predicción gráfico
df['lw_predicho'] = model3.params['edad'] * df['edad'] + model3.params['edad2'] * df['edad2']
plt.figure(figsize=(10, 6))
plt.scatter(df['edad'], df['lw_predicho'], alpha=0.6)
plt.xlabel('Edad')
plt.ylabel('lw_predicho')
plt.title('Relación salario y edad')
plt.show()

# AIC y BIC
models = [model1, model2, model3, model4]
model_names = ['Model1', 'Model2', 'Model3', 'Model4']

aic_bic = pd.DataFrame({
    'Modelo': model_names,
    'AIC': [model.aic for model in models],
    'BIC': [model.bic for model in models],
    'R2_ajustado': [model.rsquared_adj for model in models]
})
print("\n=== Comparacón de modelos (AIC/BIC) ===")
print(aic_bic)

"""### Diagnóstico del modelo"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Diagnóstico del modelo
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Ramsey
def ramsey_reset_test(model, power=3):
    """Test RESET de Ramsey"""
    y = model.model.endog
    X = model.model.exog
    y_pred = model.predict()

    # Añadir potencias de los valores predichos
    X_reset = np.column_stack([X] + [y_pred**i for i in range(2, power+1)])

    # Regresión auxiliar
    reset_model = sm.OLS(y, X_reset).fit()

    # Test F
    k = X.shape[1]
    rss_original = model.ssr
    rss_reset = reset_model.ssr
    f_stat = ((rss_original - rss_reset) / (power - 1)) / (rss_reset / (len(y) - X_reset.shape[1]))
    p_value = 1 - stats.f.cdf(f_stat, power - 1, len(y) - X_reset.shape[1])

    return f_stat, p_value

f_reset, p_reset = ramsey_reset_test(model3)
print(f"\n=== TEST RESET DE RAMSEY ===")
print(f"Estadístico F: {f_reset:.4f}")
print(f"P-valor: {p_reset:.4f}")

# VIF para multicolinealidad
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_vif(X):
    """Calcula VIF para cada variable"""
    vif_data = pd.DataFrame()
    vif_data["Variable"] = X.columns
    vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    return vif_data

X_vif = df[['educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']]
X_vif = sm.add_constant(X_vif)
vif_results = calculate_vif(X_vif)
print("\n=== FACTORES DE INFLACIÓN DE VARIANZA (VIF) ===")
print(vif_results)

# Matriz de correlaciones
corr_matrix = df[['educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']].corr()
print("\n=== MATRIZ DE CORRELACIONES ===")
print(corr_matrix)

# Para reducir multicolinealidad
edad_mean = df['edad'].mean()
df['edad_c'] = df['edad'] - edad_mean
df['edad2_c'] = df['edad_c']**2

model_centrado = smf.ols('lnsalario ~ educ + edad_c + edad2_c + urban + casado + femenino', data=df).fit()
print("\n=== MODELO CON VARIABLES CENTRADAS ===")
print(model_centrado.summary())

# Normalidad y heterocedasticidad
residuos = model3.resid

# Gráfico densidad de residuos
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
sns.kdeplot(residuos, label='Residuos')
x = np.linspace(residuos.min(), residuos.max(), 100)
plt.plot(x, stats.norm.pdf(x, residuos.mean(), residuos.std()), 'r-', label='Normal')
plt.title('Densidad de residuos')
plt.legend()

plt.subplot(1, 2, 2)
stats.probplot(residuos, dist="norm", plot=plt)
plt.title('Q-Q Plot de residuos')

plt.tight_layout()
plt.show()

# Test de normalidad
jb_stat, jb_pvalue = stats.jarque_bera(residuos)
print(f"\n=== TEST DE NORMALIDAD  ===")
print(f"Estadístico: {jb_stat:.4f}")
print(f"P-valor: {jb_pvalue:.4f}")

# Test de heterocedasticidad (Breusch-Pagan)
from statsmodels.stats.diagnostic import het_breuschpagan

bp_test = het_breuschpagan(residuos, model3.model.exog)
print(f"\n=== TEST DE HETEROCEDASTICIDAD (BREUSCH-PAGAN) ===")
print(f"Estadístico LM: {bp_test[0]:.4f}")
print(f"P-valor: {bp_test[1]:.4f}")

# Corrección con errores robustos
model3_robust = smf.ols('lnsalario ~ educ + edad + edad2 + urban + casado + femenino', data=df).fit(cov_type='HC3')
print("\n=== Model con errores robustos ===")
print(model3_robust.summary())

"""### Test de Chow y vI"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Test de Chow y variables de interacción
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Crear variables de interacción para estabilidad
for i, var in enumerate(['educ', 'edad', 'edad2', 'urban', 'casado'], 1):
    df[f'i{i}'] = df['femenino'] * df[var]

# Modelo completo
model_interacciones = smf.ols('lnsalario ~ educ + edad + edad2 + urban + casado + femenino + i1 + i2 + i3 + i4 + i5', data=df).fit()
print("\n=== Modelo completo ===")
print(model_interacciones.summary())

# Test conjunta de  interacciones
hypothesis_inter = 'i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0'
f_test_inter = model_interacciones.f_test(hypothesis_inter)

hypothesis_inter = 'i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0'
f_test_inter = model_interacciones.f_test(hypothesis_inter)

print(f"\n=== Test conjunto ===")
print(f"Estadístico F: {f_test_inter.fvalue:.4f}")
print(f"P-valor: {f_test_inter.pvalue:.4f}")
print(f"Grados de libertad: {f_test_inter.df_num}, {f_test_inter.df_denom}")

"""### Cuantílicas"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Regresiones cuantílicas
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from statsmodels.regression.quantile_regression import QuantReg

# Regresiones cuantílicas
qreg_10 = QuantReg(df['lnsalario'], sm.add_constant(df[['educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']])).fit(q=0.1)
qreg_50 = QuantReg(df['lnsalario'], sm.add_constant(df[['educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']])).fit(q=0.5)
qreg_90 = QuantReg(df['lnsalario'], sm.add_constant(df[['educ', 'edad', 'edad2', 'urban', 'casado', 'femenino']])).fit(q=0.9)

print("\n=== REGRESIÓN CUANTÍLICA (Q10) ===")
print(qreg_10.summary())
print("\n=== REGRESIÓN CUANTÍLICA (Q50 - Mediana) ===")
print(qreg_50.summary())
print("\n=== REGRESIÓN CUANTÍLICA (Q90) ===")
print(qreg_90.summary())

# Comparación dde los modelos
comparison_qreg = pd.DataFrame({
    'Cuantil': ['Q10', 'Q50', 'Q90'],
    'Intercepto': [qreg_10.params[0], qreg_50.params[0], qreg_90.params[0]],
    'educ': [qreg_10.params[1], qreg_50.params[1], qreg_90.params[1]],
    'femenino': [qreg_10.params[6], qreg_50.params[6], qreg_90.params[6]]
})
print("\n=== COMPARACIÓN REGRESIONES CUANTÍLICAS ===")
print(comparison_qreg)

# Gráfico de cuantílicas
plt.figure(figsize=(10, 6))
plt.scatter(df['educ'], df['lnsalario'], alpha=0.6, label='Datos')

# Ajustar modelos simples para gráfico
q10_simple = QuantReg(df['lnsalario'], sm.add_constant(df['educ'])).fit(q=0.1)
q90_simple = QuantReg(df['lnsalario'], sm.add_constant(df['educ'])).fit(q=0.9)
ols_simple = smf.ols('lnsalario ~ educ', data=df).fit()

x_vals = np.linspace(df['educ'].min(), df['educ'].max(), 100)
plt.plot(x_vals, ols_simple.params[0] + ols_simple.params[1] * x_vals,
         'r-', label='OLS', linewidth=2)
plt.plot(x_vals, q10_simple.params[0] + q10_simple.params[1] * x_vals,
         'g--', label='Q10', linewidth=2)
plt.plot(x_vals, q90_simple.params[0] + q90_simple.params[1] * x_vals,
         'b--', label='Q90', linewidth=2)

plt.xlabel('Años de escolaridad')
plt.ylabel('ln(salario)')
plt.title('Comparación de regresiones')
plt.legend()
plt.show()

"""## Exportar"""

# Exportar resultados de modelos
results_dict = {
    'Model1': model1.params,
    'Model2': model2.params,
    'Model3': model3.params,
    'Model4': model4.params
}

results_df = pd.DataFrame(results_dict)
results_df.to_excel('Resultado_aprox-outreg2-.xlsx')